### ISSUE TITLE
"make fortran" is not stable when parallelized

### ISSUE THREAD

**Issue by edditler** [SHTOOLS/homebrew-shtools#4] opened 2019-09-25 09:48 UTC
When trying to update shtools I get the following output:

```
○ → brew upgrade
Updating Homebrew...
==> Upgrading 1 outdated package:
shtools/shtools/shtools 4.5.2 -> 4.5.3
==> Upgrading shtools/shtools/shtools
 ==> Downloading https://github.com/SHTOOLS/SHTOOLS/archive/v4.5.3.tar.gz
Already downloaded: $HOME/Library/Caches/Homebrew/downloads/e1df3f7ccbd7d0872d283e73441c16752ee37a91c0430db29750603faf507367--SHTOOLS-4.5.3.tar.gz
==> make fortran
Last 15 lines from $HOME/Library/Logs/Homebrew/shtools/01.make:
mkdir -pv modules
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src -f Makefile all F95="gfortran" F95FLAGS="-m64 -fPIC -O3 -std=f2003 -ffast-math" LIBNAME="SHTOOLS" LAPACK_FLAGS=""
gfortran -c -m64 -fPIC -O3 -std=f2003 -ffast-math ftypes.f95
gfortran -c -m64 -fPIC -O3 -std=f2003 -ffast-math SHTOOLS.f95
gfortran -c -m64 -fPIC -O3 -std=f2003 -ffast-math FFTW3.f95
gfortran -c -m64 -fPIC -O3 -std=f2003 -ffast-math PlanetsConstants.f95
PlanetsConstants.f95:11:8:

   11 |     use ftypes
      |        1
Fatal Error: Cannot open module file 'ftypes.mod' for reading at (1): No such file or directory
compilation terminated.
make[1]: *** [PlanetsConstants.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [fortran] Error 2
```

May this be an issue with the new Xcode release?

**Comment by MarkWieczorek** [comment] 2019-09-25 10:07
Could you first try reinstalling?

```
brew uninstall shtools
brew install shtools
```

If that doesn't work, as a hack, try executing `brew install shtools` several times until it works.

The problem is that when brew runs the makefile, it runs several jobs in parallel using `make -j`. Sometimes on one of the parallel processes, the file `ftypes.mod` isn't ready yet. I have done all that is humanly possible to specify that this file is required to be built first in the file `src/Makefile`, so if anyone has any ideas on how to fix this, let me know.

Could you let me know what version of xcode you are using
```
/usr/bin/xcodebuild -version
```
And also let me know how this works out?

**Comment by MarkWieczorek** [comment] 2019-09-25 10:48
I have given up on trying to get the Makefile to build in parallel, so in the brew formula, I have added
```
ENV.deparallelize
```
which compiles each file sequentially. This is guaranteed to work, but it tables about 6 (?) times as much time to build the archive.

I'll leave this issue open to see if anyone can help.

**Comment by MarkWieczorek** [comment] 2019-09-25 11:06
I'm going to close this issue, but leave a similar issue open on the main project page. This is a problem that concerns not only brew.

**Closed as completed by MarkWieczorek** 2019-09-25 11:06 UTC

**Comment by edditler** [comment] 2019-10-07 13:02
Sorry for the late reply. I was using

```
○ → /usr/bin/xcodebuild -version
Xcode 11.0
Build version 11A420a
```

in case that still matters. `brew upgrade` did successfully upgrade the package to version 4.5.4 now.

Thank you!
